import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "./_components/sidebar";

import {Inter} from "next/font/google"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "auto"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased flex flex-row bg-gray-100 text-[#0F172A]`}
      >
        <Sidebar />
        <main className="pl-8 pt-4 h-full">
          {children}
        </main>
      </body>
    </html>
  );
}
