import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "./_components/sidebar";

import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "auto",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} border-5 flex h-screen flex-row border-gray-200 bg-gray-100 text-[#0F172A] antialiased`}
      >
        <Sidebar />
        <main className="w-full border">{children}</main>
      </body>
    </html>
  );
}
